# Generated by Django 5.1.1 on 2024-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=128)),
                ("team2", models.CharField(max_length=128)),
                ("team1_goals", models.IntegerField()),
                ("team2_goals", models.IntegerField()),
            ],
        ),
    ]
